Gold_Quiz/Areas/AdminPanel/Controllers/AdminDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Gold_Quiz.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class AdminDashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Gold_Quiz/Areas/AdminPanel/Controllers/CourseController.cs
using AutoMapper;
using Gold_Quiz.DataModel.Entities;
using Gold_Quiz.DataModel.Models;
using Gold_Quiz.DataModel.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Gold_Quiz.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]

    public class CourseController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IMapper _mapper;
        // shenasaii kodom user dare az system estefade mikone
        public readonly UserManager<ApplicationUsers> _userManager;

        public CourseController(IUnitOfWork context, UserManager<ApplicationUsers> userManager
            , IMapper mapper)
        {
            _context = context;
            _userManager = userManager;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var model = _context.coursesUW.Get(); //list doros
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CourseViewModel model)
        {
            if (ModelState.IsValid)
            {
                Courses C = new Courses
                {
                    // chon yedoone fild darim nemiaim az auto mapper estefade konim 
                    // vaghti auto mapper estefade mikonim ke hadeaghal 7-8 field dashte bashim 
                    CourseName = model.CourseName,
                    UserID = _userManager.GetUserId(HttpContext.User)
                    // id user ke dare ba systemm karmikone dar miarim 
                };
                _context.coursesUW.Create(C);
                _context.Save();
                return RedirectToAction("Index"); // boro be action index 
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        // bayad id reccord ke mikhaim edit konim ro begirim 
        public IActionResult Edit(int CourseId)
        {
            if (CourseId == 0)
            {
                return Redirect("Home/Error");
            }
            // id ro bayad dar database peyda koni va etelaat oon ro befresti be view 
            var mapModel = _mapper.Map<CourseViewModel>(_context.coursesUW.GetById(CourseId)); // <destination>  (model)
            // course id ro behesh midim be ma model ro mide
            // bayad az mapper estefade konim 
            return View(mapModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // baraye amniate // baes mishe token taghir nakone -> age taghir kard motavajeh mishe 
        public IActionResult Edit(CourseViewModel model)
        {
            if (ModelState.IsValid)
            {
                //ویرایش
                // bayad az mapper estefade konim chon faghat courseview ro darim dar sorati ke mikhaim az Course estefade konim 
                var mapModel = _mapper.Map<Courses>(model);
                _context.coursesUW.Update(mapModel);
                _context.Save();
                return RedirectToAction("Index"); // vaghti karet tamom shod boro be index
            }
            else
            {
                return View(model);
            }

        }
    }
}

Gold_Quiz/Areas/AdminPanel/Controllers/StudentManagementController.cs
using AutoMapper;
using Gold_Quiz.CommonLayer.PublicClasses;
using Gold_Quiz.DataModel.Entities;
using Gold_Quiz.DataModel.Models;
using Gold_Quiz.DataModel.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;

namespace Gold_Quiz.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class StudentManagementController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly UserManager<ApplicationUsers> _userManager;
        private readonly ICenterRepository _center;
        private readonly IMapper _mapper;
        private IWebHostEnvironment _hosting;

        public StudentManagementController(IUnitOfWork context, UserManager<ApplicationUsers> userManager,
            ICenterRepository center, IMapper mapper, IWebHostEnvironment hosting)
        {
            _context = context;
            _userManager = userManager;
            _center = center;
            _mapper = mapper;
            _hosting = hosting;
        }
        public IActionResult Index()
        {
            var model = _context.centerUsersUW.
                Get(c => c.CenterAdminID == _userManager.GetUserId(HttpContext.User) && c.Users_ST.UserType == 3, "Users_ST");
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StudentViewModel model)
        {
            if (ModelState.IsValid) // yani hame etelaat be dorosti vared shode bood
            {
                using (var tr = _context.BaseTransaction())
                {
                    // نقش عملیات را دارد
                    //Register
                    try
                    {
                        var getCenterID = _center.GetCenterID(_userManager.GetUserId(HttpContext.User));

                        var user = await _userManager.FindByNameAsync(model.UserName);
                        if (user != null)
                        {
                            // user peyda shod
                            ModelState.AddModelError("UserName", "شماره تماس شما در سیستم ثبت شده است .");// enteha neshan bede hamoon akhar ke ConfirmPassword neveshtim 
                            return View(model);
                        }

                        var mapUser = _mapper.Map<ApplicationUsers>(model);
                        mapUser.PhoneNumber = model.UserName; // phone number hamoon username ast
                        mapUser.UserType = 3;//Student
                        mapUser.IsActive = 1;// Active

                        //amaliate sabte nam
                        // 1 - ثبت کاربر در دیتابیس
                        IdentityResult result = await _userManager.CreateAsync(mapUser, "123456");// karbar dar in khat sabte nam mishe // password sade gharar midim bar aval 
                        if (result.Succeeded)
                        {
                            // 2 - ثبت نقش برای کاربر
                            await _userManager.AddToRoleAsync(mapUser, "Student");// be karbar mapuser yek role bede // Role admin be user dadim 

                            // 3 - ثبت اطلاعات دانش آموز در مرکز
                            CenterUsers CU = new CenterUsers
                            {
                                CenterAdminID = _userManager.GetUserId(HttpContext.User),// hamin usr ke dare etelaat ro submit mikone user admin ast 
                                CenterID = getCenterID,
                                CenterUserID = mapUser.Id, // id modares ya daneshamooz
                                UserType = 3
                            };
                            _context.centerUsersUW.Create(CU);

                        }
                        tr.commit();
                        _context.Save();

                        // estefade az transaction ha baraye inke ya hamash anjam beshe ya aslan anjam nashe chon mesalan vasatesh internet ghat shod moshke nakhore mesalan Role sakhte nashe az transaction estefade mikonim ke mesle yek tarakonesh kar mikone

                        return RedirectToAction("Index");
                        // 3 ja etelaat sabt mishe : 
                        //1- Role
                        //2- User
                        //3- Centers
                    }
                    catch (Exception)
                    {
                        tr.RollBack(); // hich kari anjam nade
                        return RedirectToAction("Error", "Home"); // agar error didi boro be controller => home action => error 

                    }
                }
            }
            else
            {
                //namayesh khataha
                return View(model);
            }

        }

        [HttpGet]
        public IActionResult UploadAndImportExcell()
        {
            return PartialView("_uploadAndImportExcell");
        }

        public IActionResult ExcellImport(int cellCount = 4) // tedad sotoon haye file excell ke 4 soton ast 
        {
            IFormFile file = Request.Form.Files[0]; // mitonim az tarighe in file daryaft konim 
            PublicVariable.GetExcell.Clear(); // agar etelaati ya dataii dare hazf bokon felan chon static ast

            // تغییر اسم فایل دریافتی 
            string MyFileName = Path.GetFileNameWithoutExtension(file.FileName.ToString()) + "_" +
                Guid.NewGuid() + Path.GetExtension(file.FileName.ToString());// esmesho taghir bedim name nabayad dar server tekrari bashe 

            // zakhire dar bakhsh excel file wwwroot
            string foldername = "excelfile";
            // boro dar root project va file ke inja taghir dadi upload kon dar project
            string webRootpath = _hosting.WebRootPath;  // baraye kar ba root project
            string newPath = Path.Combine(webRootpath, foldername);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
            { // agar Directory vojod nadasht 
                //ijadesh bokon 
                Directory.CreateDirectory(newPath);
                // farze inke folder va ina nabood 
            }
            if (file.Length > 0)
            {
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                ISheet sheet;
                string fullPath = Path.Combine(newPath, MyFileName);
                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                    stream.Position = 0;
                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //This will read the Excel 97-2000 formats  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook  
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //This will read 2007 Excel format  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook   
                    }
                    IRow headerRow = sheet.GetRow(0); //Get Header Row
                    //cellCount = headerRow.LastCellNum;
                    sb.Append("<table class='table'><tr>");
                    for (int j = 0; j < cellCount; j++)
                    {
                        NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);
                        if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;
                        sb.Append("<th>" + cell.ToString() + "</th>");
                    }
                    sb.Append("</tr>");
                    sb.AppendLine("<tr>");
                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
                    {
                        IRow row = sheet.GetRow(i);
                        if (row == null) continue;
                        if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;


                        for (int j = row.FirstCellNum; j < cellCount; j++)
                        {
                            if (row.GetCell(j) != null)
                            {
                                sb.Append("<td>" + row.GetCell(j).ToString() + "</td>");
                                PublicVariable.GetExcell.Add(row.GetCell(j).ToString());
                            }
                            else
                            {
                                sb.Append("<td></td>");
                                PublicVariable.GetExcell.Add("");
                            }
                        }
                        sb.AppendLine("</tr>");
                    }
                    sb.Append("</table>");
                }
            }

            return Json(new { rsb = sb.ToString(), status = "success", filename = MyFileName });
        }

        [HttpPost]
        public async Task<IActionResult> InsertInDB()
        {
            using (var transaction = _context.BaseTransaction())
            {
                try
                {
                    string getAdminId = _userManager.GetUserId(HttpContext.User);
                    var getCenterID = _center.GetCenterID(_userManager.GetUserId(HttpContext.User));

                    int gg = (PublicVariable.GetExcell.Count) / 4;
                    for (int i = 0; i < gg; i++)
                    {

Gold_Quiz/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <!-- START - MetaTags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="fa">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["AdminTitle"] - Gold Quiz</title>
    <!-- END - MetaTags -->
    <!-- START - stylesheets -->
    <link href="~/Panel/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/core.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/components.css" rel="stylesheet" type="text/css">
    @*font awsome css*@
    <link href="~/css/fontawesome5/css/all.css" rel="stylesheet" />
    <link href="~/css/customstyle.css" rel="stylesheet" />
    <!--Select2 Css / Js -->
    <link href="~/lib/select2/select2.min.css" rel="stylesheet" />

</head>
<body class="navbar-top">
    <!-- START - Main Navibar -->
    <partial name="_NavbarPartial" />
    <!-- END - Main Navibar -->
    <!-- START - Main Content -->
    <div class="page-container">

        <!-- START - Page Content -->
        <div class="page-content">

            <!-- START - Main Sidebar -->
            <partial name="_SidebarPartial" />
            <!-- END - Main Sidebar -->
            <!-- START - Main Content -->
            <div class="content-wrapper">

                <!-- START - View header -->
                <div class="page-header">
                    <div class="page-header-content">
                        <div style="padding-top:10px;">
                        </div>
                    </div>
                </div>
                <!-- END - View header -->
                <!-- Content area -->
                <div class="content">

                    <!-- START - View Content -->
                    <div class="row">
                        @RenderBody()
                        @*har view ke ma befresim inja namyesh dade mishe*@
                    </div>
                    <!-- END - View Content -->


                </div>
                <!-- /content area -->
                <!-- Footer -->

                <div class="breadcrumb-line" style="background-color:goldenrod; padding-top: 2px; border-top:1px solid gray; text-align:center; bottom:1px !important; position:fixed; width:100%;">
                    <div class="col-md-offset-2 col-md-6">
                        <span style="color: white;"> سیستم آزمون گیر <span style="color:red; font-weight:bold;">Gold Quiz</span</span>
                    </div>
                </div>

                <!-- /footer -->
            </div>
            <!-- END - Main Content -->

        </div>
        <!-- END - Page Content -->

    </div>
    <!-- END - Main Content -->
    <!--Top Loading-->
    <script type="text/javascript" src="~/Panel/assets/js/plugins/loaders/pace.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/plugins/ui/nicescroll.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/app.js"></script>
    <!--Select2 js -->
    <script src="~/lib/select2/select2.min.js"></script>
    <!-- END - theme JS files -->
    @await RenderSectionAsync("AdminScripts", required: false)

    @*Esme script ha ast requird ham nist be in maani ke niaz nist hatman neveshe beshe *@

</body>

</html>

Gold_Quiz/Areas/AdminPanel/Views/Shared/_NavbarPartial.cshtml
<div class="navbar navbar-fixed-top" style="background-color:goldenrod;">
    <div class="navbar-header" style="background-color: goldenrod;">
        <a class="navbar-brand" href="#"></a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile" style="color:black;"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle" style="color:black;"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>

    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile" style="background-color:goldenrod;">
        <ul class="nav navbar-nav">
            <li>
                <a class="sidebar-control sidebar-main-toggle hidden-xs" style="color:black;"><i class="icon-paragraph-justify3"></i></a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown" style="color:black; font-weight:bold;">

                    <span>امکانات شخصی</span>
                    <i class="caret"></i>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#"><i class="icon-user-plus"></i>پروفایل من</a></li>
                    <li>
                        <a href="#">
                            <span class="badge badge-info pull-right">3</span> <i class="icon-comment-discussion"></i>آخرین پیام ها
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-switch2"></i> خروج از سیستم</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

Gold_Quiz/Areas/AdminPanel/Views/Shared/_SidebarPartial.cshtml
<style>
    /* Copy in Sidebar Partial */
    .navigation > li.active > a {
        background-color: transparent;
        color: white !important;
        /*font-weight: bold;*/
    }

    .navigation li a {
        background-color: transparent;
        color: white !important;
    }

        .navigation li a:hover {
            background-color: transparent;
            color: yellow;
        }

    .navigation > li.active > a:focus {
        background-color: transparent;
    }

    .navigation > li.active > a:hover {
        background-color: transparent;
    }

    ul li {
        font-size: 16px;
        /*border-bottom:1px solid gray;*/
    }

        ul li ul li {
            background-color: darkgoldenrod;
            font-size: 14px;
            padding-right: 15px;
        }
</style>

<div class="sidebar sidebar-main" style="background-color:goldenrod;">
    <div class="sidebar-content">

        <!-- START - User menu -->
        <div class="sidebar-user">
            <div class="category-content">
                <div class="media">
                    <a href="#" class="media-left">
                    </a>
                    <div class="media-body">
                        <span class="media-heading text-semibold" style="color:white; font-size:16px;">دبستان عرفان</span>
                        <div class="text-size-mini text-muted">
                            <span style="color:brown;font-size:14px;">پنل ادمین</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END - User menu -->
        <!-- START - Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">

                <!-- START - Item Navigation -->
                <ul class="navigation navigation-main">

                    <!-- START - Item Navigation Header -->
                    <li class="navigation-header">
                        <span style="color:white; font-weight:bold;"> میز کار </span> <i class="icon-menu" title="صفحه اصلی"></i>
                    </li>

                    <li class="active">
                        <a asp-controller="AdminDashboard" asp-action="Index" asp-area="AdminPanel">
                            <i class="fas fa-dashboard"></i>
                            <span>پیشخوان</span>
                        </a>
                    </li>
                    <li>
                    </li>
                    <!-- END - Item Navigation Header -->
                    <!-- START - مدیریت مدرس -->
                    <li>
                        <a href="#"><i class="fas fa-chalkboard-teacher"></i><span> مدیریت مدرس </span></a>

                        <ul>
                            <li>
                                <a asp-controller="TeacherManagement" asp-action="Index"><i class="fas fa-list-alt"></i><span> لیست مدرسین </span></a>

                            </li>
                        </ul>
                    </li>
                    <!--END - مدیریت مدرس-->
                    <!-- START - مدیریت دانش آموزان -->
                    <li>
                        <a href="#"><i class="fas fa-user-graduate"></i><span> مدیریت دانش آموزان </span></a>

                        <ul>
                            <li>
                                <a asp-controller="StudentManagement" asp-action="Index"><i class="fas fa-users"></i><span> لیست دانش آموزان </span></a>
                            </li>
                        </ul>
                    </li>
                    <!-- END - مدیریت دانش آموزان -->
                    <!-- START - مدیریت دروس -->
                    <li>
                        <a href="#"><i class="fas fa-book-open"></i><span> مدیریت دروس </span></a>

                        <ul>
                            <li>
                                <a asp-area="AdminPanel" asp-controller="Course" asp-action="Index"><i class="fas fa-book-dead"></i><span> لیست دروس </span></a>
                            </li>
                        </ul>
                    </li>
                    <!-- END - مدیریت دروس -->


                </ul>
                <!-- END - Item Navigation -->

            </div>
        </div>
        <!-- END - Main navigation -->

    </div>
</div>