Gold_Quiz/Areas/AdminPanel/Controllers/TeacherManagementController.cs
using AutoMapper;
using Gold_Quiz.DataModel.Entities;
using Gold_Quiz.DataModel.Models;
using Gold_Quiz.DataModel.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Gold_Quiz.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class TeacherManagementController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly UserManager<ApplicationUsers> _userManager;
        private readonly IMapper _mapper;
        private readonly ICenterRepository _center;
        private readonly IUserRepository _user;

        public TeacherManagementController(IUnitOfWork context, ICenterRepository center,
            UserManager<ApplicationUsers> userManager, IMapper mapper, IUserRepository user)
        {
            _context = context;
            _userManager = userManager;
            _mapper = mapper;
            _center = center;
            _user = user;
        }
        public IActionResult Index()
        {
            var model = _context.centerUsersUW.
                Get(c => c.CenterAdminID == _userManager.GetUserId(HttpContext.User) && c.Users_ST.UserType == 2, "Users_ST");
            return View(model);
            // hamin admin id ke toye system hast ro bia neshon bede users haye khodesh ro neshon bede
            // dar centerusers be name moalem dastresi nadaim join ham bayad konim 
            // listi  az center users vali ba shart
            // && List moalemin bedone && feghat list kole karbaran ast 2 = moalem , 1 = Admin ..
        }

        [HttpGet] // action method az type get
        public IActionResult Create()
        {
            CourseList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeacherViewModel model, int[] CourseID) // yek vorodi array integer dare be sorate vorodi 
        {
            if (ModelState.IsValid) // yani hame etelaat be dorosti vared shode bood
            {
                using (var tr = _context.BaseTransaction())
                {
                    // نقش عملیات را دارد
                    //Register
                    try
                    {
                        var getCenterID = _center.GetCenterID(_userManager.GetUserId(HttpContext.User));
                        if (CourseID.Length == 0)
                        {
                            ModelState.AddModelError("CourseID", "لطفا حداقل یک درس انتخاب کنید .");
                            CourseList();
                            return View(model);
                        }
                        var user = await _userManager.FindByNameAsync(model.UserName);
                        if (user != null)
                        {
                            // user peyda shod
                            ModelState.AddModelError("UserName", "شماره تماس شما در سیستم ثبت شده است .");// enteha neshan bede hamoon akhar ke ConfirmPassword neveshtim 
                            return View(model);
                        }

                        var mapUser = _mapper.Map<ApplicationUsers>(model);
                        mapUser.PhoneNumber = model.UserName; // phone number hamoon username ast
                        mapUser.UserType = 2;//Teacher
                        mapUser.IsActive = 1;// Active

                        //amaliate sabte nam
                        // 1 - ثبت کاربر در دیتابیس
                        IdentityResult result = await _userManager.CreateAsync(mapUser, "123456");// karbar dar in khat sabte nam mishe // password sade gharar midim bar aval 
                        if (result.Succeeded)
                        {
                            // 2 - ثبت نقش برای کاربر
                            await _userManager.AddToRoleAsync(mapUser, "Teacher");// be karbar mapuser yek role bede // Role admin be user dadim 

                            // 3 - ثبت اطلاعات مدرس در مرکز
                            CenterUsers CU = new CenterUsers
                            {
                                CenterAdminID = _userManager.GetUserId(HttpContext.User),// hamin usr ke dare etelaat ro submit mikone user admin ast 
                                CenterID = getCenterID,
                                CenterUserID = mapUser.Id, // id modares ya daneshamooz
                                UserType = 2
                            };
                            _context.centerUsersUW.Create(CU);

                            //ثبت دروس برای معلم - 4 
                            for (int i = 0; i < CourseID.Length; i++)
                            {
                                TeacherCourse TC = new TeacherCourse
                                {
                                    TeacherID = mapUser.Id,  // 
                                    CenterID = getCenterID,
                                    CourseID = CourseID[i],
                                    TeacherAdminID = _userManager.GetUserId(HttpContext.User) // useri ke alan dare sabt etelaat anjam mide
                                };
                                _context.teacherCourseUW.Create(TC); // har bar darsi sabt mishe bayad baraye moalem ham sabt beshe
                            }

                        }
                        tr.commit();
                        _context.Save();

                        // estefade az transaction ha baraye inke ya hamash anjam beshe ya aslan anjam nashe chon mesalan vasatesh internet ghat shod moshke nakhore mesalan Role sakhte nashe az transaction estefade mikonim ke mesle yek tarakonesh kar mikone

                        return RedirectToAction("Index");
                        // 3 ja etelaat sabt mishe : 
                        //1- Role
                        //2- User
                        //3- Centers
                    }
                    catch (Exception)
                    {
                        tr.RollBack(); // hich kari anjam nade
                        return RedirectToAction("Error", "Home"); // agar error didi boro be controller => home action => error 

                    }
                }
            }
            else
            {
                //namayesh khataha
                return View(model);
            }
        }

        private void CourseList()
        {
            List<Courses> lstcourses = _context.coursesUW.Get().ToList(); //listi az course ro mikhaim namayesh bedim 
                                                                          //Courses mdl = new Courses
                                                                          //{
                                                                          //    CourseID = -1,
                                                                          //    CourseName = "... انتخاب درس"
                                                                          //    // satr ezafe kardim 
                                                                          //};
                                                                          //lstcourses.Insert(0, mdl);
            ViewBag.CourseList = lstcourses;
        }

        [HttpGet]
        public IActionResult Edit(string TeacherID)
        {
            if (TeacherID == null)
            {
                return RedirectToAction("Error", "Home");
            }
            var Teacher = _mapper.Map<TeacherViewModel>(_context.userUW.GetById(TeacherID));
            // az class application users ast vali dar view az teacherviewmodel estefade kardim pas bayad az mapper estefade konim 
            Teacher.UserID = TeacherID;
            CourseList(); // bayad seda zade shavad
            return View(Teacher);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TeacherViewModel model, int[] CourseID)
        {
            if (ModelState.IsValid) // yani hame etelaat be dorosti vared shode bood
            {
                using (var tr = _context.BaseTransaction())
                {
                    // نقش عملیات را دارد
                    //Register
                    try
                    {
                        var getCenterID = _center.GetCenterID(_userManager.GetUserId(HttpContext.User));
                        if (CourseID.Length == 0)
                        {
                            ModelState.AddModelError("CourseID", "لطفا حداقل یک درس انتخاب کنید .");
                            CourseList();
                            return View(model);
                        }

                        //1 - حذف دروس معلم 
                        var TeachercourseList =
                            _context.teacherCourseUW.Get(t => t.TeacherID == model.UserID).ToList(); // list az doros moalemi ke entekhab kardim 
                        if (TeachercourseList.Count > 0)
                        {
                            _context.teacherCourseUW.DeleteByRange(TeachercourseList);
                            _context.Save();
                        }

                        //ثبت دروس برای معلم - 2 
                        for (int i = 0; i < CourseID.Length; i++)
                        {
                            TeacherCourse TC = new TeacherCourse
                            {
                                TeacherID = model.UserID,  // 
                                CenterID = getCenterID,
                                CourseID = CourseID[i],
                                TeacherAdminID = _userManager.GetUserId(HttpContext.User) // useri ke alan dare sabt etelaat anjam mide
                            };
                            _context.teacherCourseUW.Create(TC); // har bar darsi sabt mishe bayad baraye moalem ham sabt beshe
                        }

Gold_Quiz/Areas/AdminPanel/Views/TeacherManagement/Create.cshtml
@* inja mikhaim yek teacher ro dar table users sabt konim ke usertype oon == 2 ast *@

@model TeacherViewModel
@*baraye modaresin jadid niaz be model jadid darim first name , last name , phone number har modares ro mikhaim baghie chhizaro khodemoon set mikonim *@

@{
    ViewData["AdminTitle"] = "ثبت مدرس جدید";
    List<Courses> ListCourse = ViewBag.CourseList;
}

<style>
    .select2-selection {
        border: 1px solid gray !important;
        border-radius: 0px !important;
        height: 35px !important;
        direction: rtl !important;
        color: black;
    }

    .select2-container--default .select2-selection--multiple .select2-selection__choice {
        color: black;
    }

    .select2-container--default {
        width: 100% !important;
    }

    .select2-results__options {
        text-align: right;
    }
</style>

<div class="content">
    <div class="panel panel-heading" style="box-shadow:3px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold">
            <i class="icon-newspaper2">
            </i>
            فرم ثبت مدرس جدید
        </span>
    </div>

    <div class="panel panel-body container-fluid"
         style="border-radius:2px; box-shadow:3px 1px 1px 0 gray; background-color:#dbe1f7;">
        <form asp-controller="TeacherManagement" asp-action="Create" method="post">
            <div class="col-md-8 col-md-offest-2">
                <!--Teacher First name-->
                <div>
                    <label asp-for="FirstName" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="FirstName" type="text" class="form-control custominput" placeholder="نام مدرس ..." autocomplete="off" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>

                <!--Teacher Last name-->
                <div>
                    <label asp-for="Family" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Family" type="text" class="form-control custominput" placeholder="نام خانوادگی مدرس ..." autocomplete="off" />
                        <span asp-validation-for="Family" class="text-danger"></span>
                    </div>
                </div>

                <!--Teacher User name-->
                <div>
                    <label asp-for="UserName" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="UserName" type="text" class="form-control custominput" placeholder="شماره تماس مدرس ..." autocomplete="off" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                </div>

                <!--Teacher Course Selection-->
                <div>
                    <label asp-for="UserName" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <select asp-for="CourseID" multiple asp-items="@(new SelectList(ListCourse, "CourseID", "CourseName"))" class="form-control js-multiple custominput"></select>
                        @*asp-items = etelaat az koja begir*@
                        <span asp-validation-for="CourseID" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <button type="submit"
                            class="btn pull-right btnGreen">
                        <i class="glyphicon glyphicon-ok"></i>
                        ثبت اطلاعات
                    </button>

                </div>
            </div>
        </form>
    </div>

</div>

@section AdminScripts{
    <script>
        $(document).ready(function () { // vaghti safhe load mishe yek function khahi dasht ke class js-multiple ro peyda mikone va select2 ro behesh mide
            $('.js-multiple').select2({
                placeholder: "انتخاب درس",
                allowclear: true
            });
        });
    </script>
}

Gold_Quiz/Areas/AdminPanel/Views/TeacherManagement/Edit.cshtml
@model TeacherViewModel
@inject Gold_Quiz.DataModel.Services.IUnitOfWork _context
@*// estafadeye mostaghim az  database baraye namayesh list doros moalem*@
@*baraye modaresin jadid niaz be model jadid darim first name , last name , phone number har modares ro mikhaim baghie chhizaro khodemoon set mikonim *@

@{
    ViewData["AdminTitle"] = "ویرایش مدرس";

    List<Courses> ListCourse = ViewBag.CourseList;
    // نمایش لیست دروس معلم
    // bayad mostaghim az darabase list doros moalem ro bekhonim
    var ListOfTeacherCourse = _context.teacherCourseUW.Get(t => t.TeacherID == Model.UserID)
    .Select(c => c.CourseID).ToList(); // userid dar model hamoon teacher id ast
                                       // ba esteafade az in dastoor list course id haye in teacher ro bedast miarim
                                       // hala bayad course id haro be sorateb yek reshte matni dar biarim
                                       // List course id haye yek moalem

    string ListOfCourseString = "";
    if (ListOfTeacherCourse.Count > 0)
    {
        // agar moalem dars dasht
        for (int i = 0; i < ListOfTeacherCourse.Count; i++)
        {
            ListOfCourseString += ListOfTeacherCourse[i] + ","; // tak tak id haro ezafe kon
        }
        ListOfCourseString = ListOfCourseString.Substring(0, ListOfCourseString.Length - 1); // kam kardan , akhari
    }
}

<style>
    .select2-selection {
        border: 1px solid gray !important;
        border-radius: 0px !important;
        height: 35px !important;
        direction: rtl !important;
        color: black;
    }

    .select2-container--default .select2-selection--multiple .select2-selection__choice {
        color: black;
    }

    .select2-container--default {
        width: 100% !important;
    }

    .select2-results__options {
        text-align: right;
    }
</style>

<div class="content">
    <div class="panel panel-heading" style="box-shadow:3px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold">
            <i class="icon-newspaper2">
            </i>
            فرم ویرایش اطلاعات مدرس
        </span>
    </div>

    <div class="panel panel-body container-fluid"
         style="border-radius:2px; box-shadow:3px 1px 1px 0 gray; background-color:#dbe1f7;">
        <form asp-controller="TeacherManagement" asp-action="Edit" method="post">
            <div class="col-md-8 col-md-offest-2">

                <input asp-for="UserID" hidden />

                <!--Teacher First name-->
                <div>
                    <label asp-for="FirstName" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="FirstName" type="text" class="form-control custominput" placeholder="نام مدرس ..." autocomplete="off" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>

                <!--Teacher Last name-->
                <div>
                    <label asp-for="Family" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="Family" type="text" class="form-control custominput" placeholder="نام خانوادگی مدرس ..." autocomplete="off" />
                        <span asp-validation-for="Family" class="text-danger"></span>
                    </div>
                </div>

                <!--Teacher User name-->
                <div>
                    <label asp-for="UserName" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <input asp-for="UserName" type="text" readonly class="form-control custominput" placeholder="شماره تماس مدرس ..." autocomplete="off" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                </div>

                <!--Teacher Course Selection-->
                <div>
                    <label asp-for="UserName" class="control-label col-md-3 col-xs-12"></label>
                    <div class="col-md-9 col-xs-12">
                        <select asp-for="CourseID" multiple asp-items="@(new SelectList(ListCourse, "CourseID", "CourseName"))" class="form-control js-multiple custominput"></select>
                        @*asp-items = etelaat az koja begir*@
                        <span asp-validation-for="CourseID" class="text-danger"></span>
                    </div>
                </div>

                <input hidden value="@ListOfCourseString" type="text" id="select2str" />
                @*// list course id haye yek moalem dar in input dar ghesmat script paiin add mishe*@

                <div class="col-xs-12 form-group" style="margin-top:15px;">
                    <a asp-controller="TeacherManagement" asp-action="Index" class="btn btnRed pull-right" style="margin-right:10px; ">
                        <i class="fas fa-backward"></i>
                        برگشت
                    </a>
                    <button type="submit"
                            class="btn pull-right btnGreen">
                        <i class="glyphicon glyphicon-ok"></i>
                        ثبت اطلاعات
                    </button>

                </div>
            </div>
        </form>
    </div>

</div>

@section AdminScripts{
    <script>
        $(document).ready(function () { // vaghti safhe load mishe yek function khahi dasht ke class js-multiple ro peyda mikone va select2 ro behesh mide
            $('.js-multiple').select2({
                placeholder: "انتخاب درس",
                allowclear: true
            });
        });

        var arr = $("#select2str").val().split(",");  // delimiter // yek array besaz va dar select2 namayesh bede
        $('.js-multiple').select2().val(arr).trigger('change'); // boro id haro neshon bede
    </script>
}

Gold_Quiz/Areas/AdminPanel/Views/TeacherManagement/Index.cshtml
@model IEnumerable<CenterUsers>
@*Vaghti admin vared bakhshe panel khodesh mishe betone user haye khodesh ro bebine ke mitone shamel Student ya Teacher bashe ke inja hadaf Teacher ast *@

@{
    ViewData["AdminTitle"] = "لیست مدرسین ";
    int counter = 1;
}

<style>
    .table > tbody > tr > td {
        padding: 5px 20px 2px 2px;
        /*padding tak tak cell haro taghir mide*/
    }
</style>
<div class="content">
    @*andaze contect besho*@


    <div class="panel panel-heading" style="box-shadow:3px 1px 1px 0 gray; border-radius:2px;">
        <span style="font-weight:bold;">
            <i class="fas chalkboard-teacher"></i>
            لیست مدرسین
        </span>
    </div>

    <div style="margin-bottom:5px;">
        <a class="btn btnBlue" asp-area="AdminPanel" asp-controller="TeacherManagement" asp-action="Create">
            <i class="glyphicon glyphicon-plus"></i>
            ثبت مدرس جدید
        </a>
    </div>

    <div class="panel panel-body container-fluid"
         style="border-radius:2px; box-shadow:3px 1px 1px 0 gray; background-color:#dbe1f7;">

        <div class="table-responsive" style="border:1px solid gray; border-radius:2px; box-shadow:3px 3px 3px 0 gray;">
            <table class="table table-bordered" style="background-color:whitesmoke;">
                <thead>
                    <tr style="font-size: 14px; font-weight: bold; background-color: #aca8ef;">
                        <td style="width:40px;">ردیف</td>
                        <td>نام معلم</td>
                        <td>نام خانوادگی معلم</td>
                        <td>شماره تماس</td>
                        <td>وضعیت</td>
                        <td style="width:220px;">عملیات</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        @*model ro darim daryaft mikonim az controller

                    counter = shomare radfe
                    *@
                        <tr style="font-size:13px;">
                            <td style="width:60px; text-align:center;">@counter</td>
                            <td style="text-align:right; white-space:pre-line">@item.Users_ST.FirstName</td>
                            <td style="text-align:right; white-space:pre-line">@item.Users_ST.Family</td>
                            <td style="text-align:right; white-space:pre-line">@item.Users_ST.UserName</td>
                            <td style="padding-top:auto; background-color:@(item.Users_ST.IsActive == 1 ? "#96e796" : "#e9abab"); text-align:right; white-space:pre-line">
                                @(item.Users_ST.IsActive == 1 ? "فعال" : "غیرفعال")
                            </td>
                            <td>
                                <div class="row">
                                    <a asp-controller="TeacherManagement" asp-action="Edit" asp-route-TeacherID="@item.CenterUserID" style="height:30px; width:80px; font-size:10px; margin-bottom:3px;">
                                        <i class="glyphicon glyphicon-edit"></i>
                                        ویرایش
                                    </a>
                                </div>
                            </td>
                        </tr>
                        counter++;
                    }
                </tbody>

            </table>
        </div>

    </div>

</div>